"""
Configuration management using pydantic-settings.

Uses a lazy-loading pattern so that importing this module does NOT
crash when a .env file is absent (e.g., during unit tests).
"""

import datetime
from functools import lru_cache
from pydantic_settings import BaseSettings, SettingsConfigDict
from pydantic import Field


class Settings(BaseSettings):
    """Application settings loaded from environment variables / .env file."""

    # Dhan API
    dhan_client_id: str = Field(default="", alias="DHAN_CLIENT_ID")
    dhan_pin: str = Field(default="", alias="DHAN_PIN")
    dhan_totp_secret: str = Field(default="", alias="DHAN_TOTP_SECRET")

    # Comma-separated list of "NAME:SECURITY_ID" pairs
    # e.g. "RELIANCE:11536,TCS:3456"
    symbol_security_ids: str = Field(default="", alias="SYMBOL_SECURITY_IDS")

    # Strategy settings
    orb_start_time: str = Field(default="09:15", alias="ORB_START_TIME")
    orb_end_time: str = Field(default="09:30", alias="ORB_END_TIME")
    min_volume_threshold: int = Field(default=10000, alias="MIN_VOLUME_THRESHOLD")
    risk_reward_ratio: float = Field(default=1.0, alias="RISK_REWARD_RATIO")
    time_based_exit: str = Field(default="15:15", alias="TIME_BASED_EXIT")
    screener_top_n: int = Field(default=5, alias="SCREENER_TOP_N")

    # Webex
    webex_token: str = Field(default="", alias="WEBEX_TOKEN")
    webex_room_id: str = Field(default="", alias="WEBEX_ROOM_ID")

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        populate_by_name=True,
    )

    # ── Derived helpers ──────────────────────────────────────────────

    @property
    def security_id_map(self) -> dict[str, str]:
        """Returns {human_name: security_id} mapping.

        If trade_plan.json exists (generated by intraday_trigger.py), it uses that.
        Otherwise falls back to the .env SYMBOL_SECURITY_IDS.
        """
        import os
        import json
        if os.path.exists("trade_plan.json"):
            try:
                with open("trade_plan.json", "r") as f:
                    plan = json.load(f)
                    if plan:  # Use if not empty
                        return plan
            except Exception:
                pass

        mapping: dict[str, str] = {}
        for token in self.symbol_security_ids.split(","):
            token = token.strip()
            if not token:
                continue
            if ":" in token:
                name, sec_id = token.split(":", 1)
                mapping[name.strip()] = sec_id.strip()
            else:
                mapping[token] = token
        return mapping

    @property
    def security_ids(self) -> list[str]:
        """Flat list of security IDs."""
        return list(self.security_id_map.values())

    @property
    def security_id_to_name(self) -> dict[str, str]:
        """Reverse mapping: security_id → human name."""
        return {v: k for k, v in self.security_id_map.items()}

    @property
    def orb_start_time_parsed(self) -> datetime.time:
        return datetime.datetime.strptime(self.orb_start_time, "%H:%M").time()

    @property
    def orb_end_time_parsed(self) -> datetime.time:
        return datetime.datetime.strptime(self.orb_end_time, "%H:%M").time()

    @property
    def time_based_exit_parsed(self) -> datetime.time:
        return datetime.datetime.strptime(self.time_based_exit, "%H:%M").time()


@lru_cache(maxsize=1)
def get_config() -> Settings:
    """Lazy singleton — only reads .env when first called."""
    return Settings()
